FROM --platform=linux/amd64 node:18

ENV DATABASE_URL="DATABASE_URL"
ENV JWT_SECRET="JWT_SECRET"
ENV USER_SERVICE_URL="USER_SERVICE_URL"
ENV CATALOG_SERVICE_URL="CATALOG_SERVICE_URL"
ENV STATUS_SERVICE_URL="STATUS_SERVICE_URL"
ENV PAYMENT_SERVICE_URL="PAYMENT_SERVICE_URL"

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./

RUN yarn install

COPY . .

RUN yarn prisma generate

EXPOSE 3003

CMD yarn dev